### ISSUE TITLE
Regarding models and checkpoints

### ISSUE THREAD

**Issue by bharadwajdhornala** [aghinsa/SketchTo3D#1]
Hi @aghinsa @vishnurj99 I am exploring in testing models. Can you please provide the pre-trained models and checkpoints, so that I can start my test process.

**Comment by aghinsa** [comment]
@bharadwajdhornala Sorry,this was done long before,we lost the ckpts.

**Comment by bharadwajdhornala** [comment]
@aghinsa Thanks for the code.
